apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    timeout: 30s
  
  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100

  - name: Alertmanager
    type: prometheus
    access: proxy
    url: http://localhost:9093  # Default port for Alertmanager
    isDefault: false
    timeout: 30s  